name: Snyk Security

permissions:
  issues: write
  packages: none
on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Snyk
        run: |
          npm install -g snyk

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk_output=$(snyk test --file=requirements.txt --all-projects --json)

          # Check if there are vulnerabilities
          if [[ $snyk_output == *"vulnerabilities"* ]]; then
            echo "Vulnerabilities found. Creating pull request for security fixes..."

            # Create a new branch for security fixes
            git checkout -b security-fixes
            # Perform automatic fixes here if possible

            # Commit and push the changes
            git add .
            git commit -m "Fix security vulnerabilities"
            git push origin security-fixes

            # Create a pull request
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/pulls \
              -d "{\"title\":\"Security Fixes\",\"body\":\"Automated security fixes\",\"head\":\"security-fixes\",\"base\":\"master\"}"
          else
            echo "No vulnerabilities found."
          fi

      - name: Run Flask tests
        run: |
          python -m unittest discover -s tests
