name: Snyk Security Scan

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Snyk
        run: |
          npm install -g snyk

      - name: Run Snyk to check for vulnerabilities
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk auth $SNYK_TOKEN
          snyk test --file=requirements.txt --json > snyk-output.json

      - name: Display Snyk output
        run: |
          cat snyk-output.json
